### PR TITLE
Fix build problems with grpc (at least) 1.54

### PR DESCRIPTION
**Pull request by jengelh**

### CODE REVIEW

**Comment by johnwvmw** [comment]
@jengelh 

Hi Jan,

Thanks you very much for submitting this pull request.   I have filed an internal problem report to pick up this set of changes.

As we support the open-vm-tools source release for a wide range of Linux releases using different versions of tools, we will need to test the build of open-vm-tools across that matrix.   Nothing expect to be difficult, simply time consuming.

In the meantime, could you provide some additional information?

On what Linux release(s) have you built open-vm-tools with these build change?

- What version of autoconf and automake?
- What version of libtools?

Thanks again for this pull request.

**Comment by jengelh** [comment]
autoconf 2.71, automake 1.16.5, libtool 2.4.7 with #673

**Comment by johnwvmw** [comment]
HI Jan,

This pull request has already been incorporated in the next major release of open-vm-tools.   There was one slight modification to the configure.ac change that you proposed.

The stand-alone "PKG_CHECK_MODULES([grpcxx], [grpc++ >= 1.3.2])"  caused any build not providing a grpc++ package or having decided not to build the containerInfo plugin to fail.   Since containerInfo is an optionsal plugin, the configure.AC logic allows a builder to enable, disable or "auto" configure the containerInfo plugin build.    Auto configuration provides for a check of important packages and tools necessary to build containerInfo and skip the build if the necessary pieces are not available.   If the builder specifically specified "--enable-containerinfo" and something is missing the ./configure command will error out.

We addressed this by incorporating PKG_CHECK_MODULES in the pass argument of the existing 
   AC_VMW_CHECK_LIBXX([grpc++],
                      [GRPC],
                      [grpc++],
                      [],
                      [1.3.2],
                      [grpc++/grpc++.h],
                      [],
                      [PKG_CHECK_MODULES([grpcxx], [grpc++ >= 1.3.2])],
                      [AC_VMW_CONTAINERINFO_MSG(["grpc++ >= 1.3.2"])])
                      
 relying on the PKG_CHECK_MODULES to obtain the flags/options from the .pc file.
 
 Thanks again for you submission.

**Comment by johnwvmw** [comment]
In open-vm-tools 12.3.0 release.

**Pull request closed without merging**
