### PR TITLE
Propagate new gdk-pixbuf-xlib include location

### PR DESCRIPTION
**Pull request by tteggel**

### CODE REVIEW

**Comment by oliverkurth** [comment]
@tteggel , can you please show the error you are seeing when trying to build without this fix, and how we can reproduce it?

**Comment by tteggel** [comment]
```
appUtilX11.c:41:10: fatal error: gdk-pixbuf-xlib/gdk-pixbuf-xlib.h: No such file or directory
   41 | #include <gdk-pixbuf-xlib/gdk-pixbuf-xlib.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I see this problem when building on a platform (NixOS) where `gdk-pixbuf` package is built without x11 support enabled (`-Dx11=false`). 

A check for the deprecated API was put in a while ago in 7397d21 but AFAICT the lvar was never plumbed in. This used to be OK until recently because `gdk-pixbuf-xlib` was built as part of the `gdk-pixbuf` package and the headers got pulled in through the `@GTK_CPPFLAGS@` substitution as `gdk-pixbuf` is a dep of GTK. However, now that `gdk-pixbuf-xlib` is a separate package it is no longer included as part of `gdk-pixbuf` and therefore needs to be referenced explicitly where it's needed. I expect other distros to make this change sooner or later too.

To reproduce in a docker-based nix environment: 
```
docker run -it --rm nixos/nix sh

#Get the patched build env
mkdir ~/tmpdev && cd ~/tmpdev
nix-env --install git
git clone --depth=1 https://github.com/tteggel/nixpkgs -b fix-open-vm-tools-gdk-pixbuf-xlib

#Drop in to hermetic build env
export NIXPKGS=~/tmpdev/nixpkgs
nix-shell $NIXPKGS -A open-vm-tools

#Do the build: this will succeed as the patch in this PR is applied in the branch that you cloned above
genericBuild

#Comment out L28 of ~/tmpdev/nixpkgs/pkgs/applications/virtualization/open-vm-tools/default.nix
#Re-enter the build env
cd ../..
exit
rm -rf sources
nix-shell $NIXPKGS -A open-vm-tools
genericBuild # build fails even though autoconf has found the lib
```

More details on working with the nix build env: https://nixos.wiki/wiki/Nixpkgs/Create_and_debug_packages

Related NixOS issues: 
Package build failure: https://github.com/NixOS/nixpkgs/issues/90544
Move and deprecate gdk-pixbuf-xlib: https://github.com/NixOS/nixpkgs/pull/88086 and https://github.com/NixOS/nixpkgs/issues/74272

Hope this helps @oliverkurth?

**Comment by oliverkurth** [comment]
Got it. Thank you for the detailed instructions!

**Comment by stanguturi** [comment]
Fixed in commit 92022a07d524a16cccc71e44f4cbbbafdd1062bf.

**Pull request closed without merging**
