### PR TITLE
Linux: change to posix style

### PR DESCRIPTION
**Pull request by DimStar77**
replace it by defined(**linux**)

### CODE REVIEW

**Comment by JonathonReinhart** [comment]
Care to elaborate on this change? Under what circumstances is `__linux__`  defined as opposed to `linux`?

**Comment by DimStar77** [comment]
Sure.. nothing easier than that.

Take this very dummy c++ 'code':
```
#if defined(linux)
  #warning linux is defined
#endif
#if defined(__linux__)
  #warning __linux__ is defined
#endif

int main() {
  return 0;
}

```

then compile it twice, once using:

> g++ test.cpp 

> test.cpp:4:4: warning: #warning linux is defined [-Wcpp]
>    #warning linux is defined
>     ^
> test.cpp:7:4: warning: #warning __linux__ is defined [-Wcpp]
>    #warning __linux__ is defined
> 
> 

And once using

> 
> g++ test.cpp -std=c++11
> test.cpp:7:4: warning: #warning __linux__ is defined [-Wcpp]
>    #warning __linux__ is defined
>     ^
> 

Building using c++11 standard does NOT provide the linux defines...
and c++11 is mandatory nowadays when building against recent stack of libsigc++ / libglibmm

**Comment by JonathonReinhart** [comment]
Thanks @DimStar77. This was mainly for my own curiosity, but it may help get this PR merged, too. That is, if anyone from @vmware pays any attention to it.

**Comment by bzed** [comment]
In the meantime compiling with -std=gnu++11  works well :)

**Comment by mikini** [comment]
Confusing read! For anyone also puzzled by the thread above and maybe not looking at the patch, notice the text emphasized in bold and surround those with __. In the markdown formatting used here double underscore, as in the standard compiler defines, are translated into __bold__ text unless marked otherwise.

Original PR text 'code' quoted:
`replace it by defined(__linux__)`

And the gcc output (my execution):
```
$ g++ test.cpp 
test.cpp:2:4: warning: #warning linux is defined [-Wcpp]
   #warning linux is defined
    ^
test.cpp:5:4: warning: #warning __linux__ is defined [-Wcpp]
   #warning __linux__ is defined
    ^
$ g++ test.cpp -std=c++11
test.cpp:5:4: warning: #warning __linux__ is defined [-Wcpp]
   #warning __linux__ is defined
    ^
```

**Comment by stanguturi** [comment]
Thanks. We have created an internal bug to track it.

**Pull request closed without merging**
